import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration implements MigrationInterface {
    name = 'Migration1737003471997'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS auth`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS storage`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS meta`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS messages`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS functions`);

        await queryRunner.query(`CREATE TABLE "meta"."variables" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "resourceType" character varying(100) NOT NULL, "resourceInternalId" character varying(255), "resourceId" character varying(255), "key" character varying(255), "value" character varying(8192) NOT NULL, CONSTRAINT "PK_f580ac42e4506f3e176b0afee9e" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_fulltext_search" ON "meta"."variables" ("search") `);
        await queryRunner.query(`CREATE INDEX "_key_key" ON "meta"."variables" ("key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "_key_uniqueKey" ON "meta"."variables" ("resourceId", "key", "resourceType") `);
        await queryRunner.query(`CREATE INDEX "_key_resourceId_resourceType" ON "meta"."variables" ("resourceId", "resourceType") `);
        await queryRunner.query(`CREATE INDEX "_key_resourceType" ON "meta"."variables" ("resourceType") `);
        await queryRunner.query(`CREATE INDEX "_key_resourceInternalId" ON "meta"."variables" ("resourceInternalId") `);
        await queryRunner.query(`CREATE TABLE "meta"."stats" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "metric" character varying(255) NOT NULL, "region" character varying(255) NOT NULL, "value" integer NOT NULL, "time" TIMESTAMP WITH TIME ZONE, "period" character varying(4) NOT NULL, CONSTRAINT "PK_8c54bf67bd417fcfa6e090048b5" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_key_metric_period_time" ON "meta"."stats" ("metric", "period", "time") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "_key_period_time" ON "meta"."stats" ("period", "time") `);
        await queryRunner.query(`CREATE INDEX "_key_time" ON "meta"."stats" ("time") `);
        await queryRunner.query(`CREATE TABLE "meta"."migrations" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "status" character varying(255) NOT NULL, "stage" character varying(255) NOT NULL, "source" character varying(8192) NOT NULL, "credentials" character varying(65536), "resources" character varying(255) array NOT NULL, "statusCounters" character varying(3000) NOT NULL, "resourceData" character varying(131070) NOT NULL, "errors" character varying(65535) array NOT NULL, CONSTRAINT "PK_cd5516ced218eada65c90651144" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_fulltext__search" ON "meta"."migrations" ("search") `);
        await queryRunner.query(`CREATE INDEX "_key_source" ON "meta"."migrations" ("source") `);
        await queryRunner.query(`CREATE INDEX "_key_stage" ON "meta"."migrations" ("stage") `);
        await queryRunner.query(`CREATE INDEX "_key_status" ON "meta"."migrations" ("status") `);
        await queryRunner.query(`CREATE TABLE "meta"."databases" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "name" character varying(256) NOT NULL, "enabled" boolean DEFAULT true, CONSTRAINT "PK_dd41269666a98b929a2b1fb8f4d" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f56ebcf8cba238205136aa00f" ON "meta"."databases" ("name") `);
        await queryRunner.query(`CREATE TABLE "auth"."tokens" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying, "type" integer NOT NULL, "secret" character varying(512), "expire" TIMESTAMP, "userAgent" character varying(16384), "ip" character varying(45), "user_$id" character varying, CONSTRAINT "PK_c503843cd3330072b824de95627" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54ff822a5a8ac32ef4c49a76b5" ON "auth"."tokens" ("user_$id") `);
        await queryRunner.query(`CREATE TABLE "auth"."authenticators" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying, "type" character varying(255), "verified" boolean DEFAULT false, "data" text, "user_$id" character varying, CONSTRAINT "PK_6c9e4f5c152a6d155524d851166" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "auth"."challenges" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying, "type" character varying(255), "token" character varying(512), "code" character varying(512), "expire" TIMESTAMP WITH TIME ZONE, "user_$id" character varying, CONSTRAINT "PK_54ac183e1843cd3869bf548589e" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_id" ON "auth"."challenges" ("user_$id") `);
        await queryRunner.query(`CREATE TABLE "auth"."sessions" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying, "provider" character varying(128), "providerUid" character varying(2048), "providerAccessToken" character varying(16384), "providerAccessTokenExpiry" TIMESTAMP WITH TIME ZONE, "providerRefreshToken" character varying(16384), "secret" character varying(512), "userAgent" character varying(16384), "ip" character varying(45), "countryCode" character varying(2), "osCode" character varying(256), "osName" character varying(256), "osVersion" character varying(256), "clientType" character varying(256), "clientCode" character varying(256), "clientName" character varying(256), "clientVersion" character varying(256), "clientEngine" character varying(256), "clientEngineVersion" character varying(256), "deviceName" character varying(256), "deviceBrand" character varying(256), "deviceModel" character varying(256), "factors" text, "expire" TIMESTAMP WITH TIME ZONE NOT NULL, "mfaUpdatedAt" TIMESTAMP WITH TIME ZONE, "user_$id" character varying, CONSTRAINT "PK_d261b647fdf316891ffc62d69e5" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "auth"."teams" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "name" character varying(128), "total" integer, "prefs" json DEFAULT '{}', CONSTRAINT "PK_23483d98c33d3237f6c4f1ea2e5" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48c0c32e6247a2de155baeaf98" ON "auth"."teams" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6ada59c75ff2761704cccebd8" ON "auth"."teams" ("total") `);
        await queryRunner.query(`CREATE TABLE "auth"."memberships" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying, "teamId" character varying, "roles" character varying(128) array, "invited" TIMESTAMP WITH TIME ZONE, "joined" TIMESTAMP WITH TIME ZONE, "confirm" boolean, "secret" character varying(256), "user_$id" character varying, "team_$id" character varying, CONSTRAINT "PK_14f71cf19c29e3ba74d28cf6219" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "confirm_index" ON "auth"."memberships" ("confirm") `);
        await queryRunner.query(`CREATE INDEX "joined_index" ON "auth"."memberships" ("joined") `);
        await queryRunner.query(`CREATE INDEX "invited_index" ON "auth"."memberships" ("invited") `);
        await queryRunner.query(`CREATE INDEX "teamId_index" ON "auth"."memberships" ("teamId") `);
        await queryRunner.query(`CREATE INDEX "userId_index" ON "auth"."memberships" ("userId") `);
        await queryRunner.query(`CREATE INDEX "search_index" ON "auth"."memberships" ("search") `);
        await queryRunner.query(`CREATE INDEX "team_index" ON "auth"."memberships" ("team_$id") `);
        await queryRunner.query(`CREATE INDEX "user_index" ON "auth"."memberships" ("user_$id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dba610eddac5ad4aed9a1f15a0" ON "auth"."memberships" ("team_$id", "user_$id") `);
        await queryRunner.query(`CREATE TABLE "messages"."topics" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "name" character varying(128) NOT NULL, "subscribe" character varying(128) array, "emailTotal" integer DEFAULT '0', "smsTotal" integer DEFAULT '0', "pushTotal" integer DEFAULT '0', CONSTRAINT "PK_7901e30e38b273a0b3a2b970ad0" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1304b1c61016e63f60cd147ce6" ON "messages"."topics" ("name") `);
        await queryRunner.query(`CREATE TABLE "messages"."providers" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "name" character varying(128) NOT NULL, "provider" character varying(128) NOT NULL, "type" character varying(128) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "credentials" character varying(16384) NOT NULL, "options" character varying(16384) DEFAULT '', CONSTRAINT "PK_a0a68a858e80ede0570a9f276a8" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d735474e539e674ba3702eddc4" ON "messages"."providers" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6e65bb1ecd94653de7b16bb80" ON "messages"."providers" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_06250375d112fc6ec96ca3ee7c" ON "messages"."providers" ("type") `);
        await queryRunner.query(`CREATE TABLE "messages"."targets" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying NOT NULL, "sessionId" character varying(255), "session" character varying(255), "providerType" character varying(255) NOT NULL, "providerId" character varying, "identifier" character varying(255) NOT NULL, "name" character varying(255), "expired" boolean DEFAULT false, "user_$id" character varying, "provider_$id" character varying, CONSTRAINT "identifire_type" UNIQUE ("identifier", "providerType"), CONSTRAINT "PK_eab5dcb25c15ed3c205f21d06c4" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "auth"."identities" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "userId" character varying NOT NULL, "provider" character varying(128) NOT NULL, "providerUid" character varying(2048) NOT NULL, "providerEmail" character varying(320) NOT NULL, "providerAccessToken" character varying(16384) NOT NULL, "providerAccessTokenExpiry" TIMESTAMP WITH TIME ZONE, "providerRefreshToken" character varying(16384) NOT NULL, "secrets" character varying(16384) NOT NULL, "user_$id" character varying, CONSTRAINT "PK_0d6e0aca498aea8938b1d0ee68d" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_key_providerAccessTokenExpiry" ON "auth"."identities" ("providerAccessTokenExpiry") `);
        await queryRunner.query(`CREATE INDEX "_key_providerEmail" ON "auth"."identities" ("providerEmail") `);
        await queryRunner.query(`CREATE INDEX "_key_providerUid" ON "auth"."identities" ("providerUid") `);
        await queryRunner.query(`CREATE INDEX "_key_provider" ON "auth"."identities" ("provider") `);
        await queryRunner.query(`CREATE INDEX "_key_userInternalId" ON "auth"."identities" ("user_$id") `);
        await queryRunner.query(`CREATE INDEX "_key_userId" ON "auth"."identities" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "_key_provider_providerUid" ON "auth"."identities" ("provider", "providerUid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "_key_userInternalId_provider_providerUid" ON "auth"."identities" ("user_$id", "provider", "providerUid") `);
        await queryRunner.query(`CREATE TABLE "auth"."users" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "name" character varying(256), "email" character varying(320), "phone" character varying(16), "status" boolean, "labels" character varying(128) array, "passwordHistory" character varying(16384) array, "password" character varying(16384), "hash" character varying(256), "hashOptions" json, "passwordUpdate" TIMESTAMP, "prefs" json, "registration" TIMESTAMP, "emailVerification" boolean, "phoneVerification" boolean, "reset" boolean, "mfa" boolean, "mfaRecoveryCodes" character varying(256) array, "accessedAt" TIMESTAMP, CONSTRAINT "PK_46c438e5a956fb9c3e86e73e321" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ACCESSED_AT" ON "auth"."users" ("accessedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_SEARCH" ON "auth"."users" ("search") `);
        await queryRunner.query(`CREATE INDEX "IDX_PHONE_VERIFICATION" ON "auth"."users" ("phoneVerification") `);
        await queryRunner.query(`CREATE INDEX "IDX_EMAIL_VERIFICATION" ON "auth"."users" ("emailVerification") `);
        await queryRunner.query(`CREATE INDEX "IDX_REGISTRATION" ON "auth"."users" ("registration") `);
        await queryRunner.query(`CREATE INDEX "IDX_PASSWORD_UPDATE" ON "auth"."users" ("passwordUpdate") `);
        await queryRunner.query(`CREATE INDEX "IDX_STATUS" ON "auth"."users" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PHONE" ON "auth"."users" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_EMAIL" ON "auth"."users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_NAME" ON "auth"."users" ("name") `);
        await queryRunner.query(`CREATE TABLE "storage"."buckets" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "enabled" boolean NOT NULL DEFAULT true, "name" character varying(128) NOT NULL, "fileSecurity" boolean NOT NULL DEFAULT false, "maximumFileSize" integer NOT NULL, "allowedFileExtensions" text NOT NULL, "compression" character varying(10) NOT NULL, "encryption" boolean NOT NULL DEFAULT true, "antivirus" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3d88ba2ec13d9ee03172bab45e1" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "storage"."files" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "bucketId" character varying NOT NULL, "name" character varying(2048) NOT NULL, "path" character varying(2048) NOT NULL, "signature" character varying(2048) NOT NULL, "mimeType" character varying(255) NOT NULL, "metadata" character varying(75000) NOT NULL, "sizeOriginal" integer NOT NULL, "sizeActual" integer NOT NULL, "algorithm" character varying(255) NOT NULL, "comment" character varying(2048) NOT NULL, "openSSLVersion" character varying(64) NOT NULL, "openSSLCipher" character varying(64) NOT NULL, "openSSLTag" character varying(2048) NOT NULL, "openSSLIV" character varying(2048) NOT NULL, "chunksTotal" integer NOT NULL, "chunksUploaded" integer NOT NULL, "bucket_$id" character varying, CONSTRAINT "PK_aac3191a9e99bcdb7ef95b3fd68" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03457cb4a0bd785d24201481f6" ON "storage"."files" ("bucketId") `);
        await queryRunner.query(`CREATE INDEX "IDX_332d10755187ac3c580e21fbc0" ON "storage"."files" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_aacdd3a68ed158c5b526d67276" ON "storage"."files" ("signature") `);
        await queryRunner.query(`CREATE INDEX "IDX_389d4090f38da709582e7e3a95" ON "storage"."files" ("mimeType") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1d014cb180d27ab17fc21be50" ON "storage"."files" ("sizeOriginal") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8e7903f3a8a0a28a49f6b4886" ON "storage"."files" ("chunksTotal") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfced34fec53fd4205673bec3f" ON "storage"."files" ("chunksUploaded") `);
        await queryRunner.query(`CREATE TABLE "messages"."subscribers" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "targetId" character varying(128) NOT NULL, "targetInternalId" character varying(128) NOT NULL, "userId" character varying(128) NOT NULL, "userInternalId" character varying(128) NOT NULL, "topicId" character varying(128) NOT NULL, "topicInternalId" character varying(128) NOT NULL, "providerType" character varying(128) NOT NULL, CONSTRAINT "PK_5ccf6d6820e4cf67e07b7ea2cab" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1198809f29d22accb0143684ff" ON "messages"."subscribers" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_64f26a3234a4bac78f6b6e9523" ON "messages"."subscribers" ("targetInternalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e82da94a504e2d6dff5c9f393" ON "messages"."subscribers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b5f276933ed75028216a4a843" ON "messages"."subscribers" ("userInternalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d966300036db0e1ac00fa51c32" ON "messages"."subscribers" ("topicId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd461838f998443c5441989db5" ON "messages"."subscribers" ("topicInternalId") `);
        await queryRunner.query(`CREATE TABLE "messages"."messages" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "providerType" character varying(128) NOT NULL, "status" character varying(128) NOT NULL DEFAULT 'processing', "data" text NOT NULL, "topics" character varying(21845) array DEFAULT '{}', "users" character varying(21845) array DEFAULT '{}', "targets" character varying(21845) array DEFAULT '{}', "scheduledAt" TIMESTAMP, "scheduleInternalId" character varying(128), "scheduleId" character varying(128), "deliveredAt" TIMESTAMP, "deliveryErrors" text array, "deliveredTotal" integer DEFAULT '0', CONSTRAINT "PK_79fc28532440f34f2d1e725940d" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35000359daf153b15b27ee21e2" ON "messages"."messages" ("providerType") `);
        await queryRunner.query(`CREATE INDEX "idx_schedule_id" ON "messages"."messages" ("scheduleId") `);
        await queryRunner.query(`CREATE INDEX "idx_schedule_internal_id" ON "messages"."messages" ("scheduleInternalId") `);
        await queryRunner.query(`CREATE INDEX "idx_scheduled_at" ON "messages"."messages" ("scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "idx_status" ON "messages"."messages" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_type" ON "messages"."messages" ("providerType") `);
        await queryRunner.query(`CREATE TABLE "functions"."functions" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "execute" character varying(128) array, "name" character varying(2048), "enabled" boolean NOT NULL, "live" boolean NOT NULL, "installationId" character varying(255), "installationInternalId" character varying(255), "providerRepositoryId" character varying(255), "repositoryId" character varying(255), "repositoryInternalId" character varying(255), "providerBranch" character varying(255), "providerRootDirectory" character varying(255), "providerSilentMode" boolean DEFAULT false, "logging" boolean NOT NULL, "runtime" character varying(2048), "deploymentInternalId" character varying(255), "deployment" character varying(255), "vars" character varying(16384), "varsProject" character varying(16384), "events" character varying(256) array, "scheduleInternalId" character varying(255), "scheduleId" character varying(255), "schedule" character varying(128), "timeout" integer, "version" character varying(8) DEFAULT 'v4', "entrypoint" character varying(16384), "commands" character varying(16384), "specification" character varying(128) DEFAULT '', "scopes" character varying(255) array, CONSTRAINT "PK_18de5ce7c7969689b86a25ab7bf" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_key_idx_deployment" ON "functions"."functions" ("deployment") `);
        await queryRunner.query(`CREATE INDEX "_key_runtime" ON "functions"."functions" ("runtime") `);
        await queryRunner.query(`CREATE INDEX "_key_repositoryInternalId" ON "functions"."functions" ("repositoryInternalId") `);
        await queryRunner.query(`CREATE INDEX "_key_repositoryId" ON "functions"."functions" ("repositoryId") `);
        await queryRunner.query(`CREATE INDEX "_key_providerRepositoryId" ON "functions"."functions" ("providerRepositoryId") `);
        await queryRunner.query(`CREATE INDEX "_key_installationInternalId" ON "functions"."functions" ("installationInternalId") `);
        await queryRunner.query(`CREATE INDEX "_key_installationId" ON "functions"."functions" ("installationId") `);
        await queryRunner.query(`CREATE INDEX "_key_enabled" ON "functions"."functions" ("enabled") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "_key_name" ON "functions"."functions" ("name") `);
        await queryRunner.query(`CREATE INDEX "_key__search" ON "functions"."functions" ("search") `);
        await queryRunner.query(`CREATE TABLE "functions"."executions" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "functionInternalId" character varying(255), "functionId" character varying(255), "deploymentInternalId" character varying(255), "deploymentId" character varying(255), "trigger" character varying(128), "status" character varying(128), "duration" double precision, "errors" character varying(1000000), "logs" character varying(1000000), "requestMethod" character varying(128), "requestPath" character varying(2048), "requestHeaders" character varying(16384), "responseStatusCode" integer, "responseHeaders" character varying(16384), "scheduledAt" TIMESTAMP WITH TIME ZONE, "scheduleInternalId" character varying(255), "scheduleId" character varying(255), CONSTRAINT "PK_ee20ed71d697780495a4b8f6865" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_key_duration" ON "functions"."executions" ("duration") `);
        await queryRunner.query(`CREATE INDEX "_key_responseStatusCode" ON "functions"."executions" ("responseStatusCode") `);
        await queryRunner.query(`CREATE INDEX "_key_deploymentId" ON "functions"."executions" ("deploymentId") `);
        await queryRunner.query(`CREATE INDEX "_key_requestPath" ON "functions"."executions" ("requestPath") `);
        await queryRunner.query(`CREATE INDEX "_key_requestMethod" ON "functions"."executions" ("requestMethod") `);
        await queryRunner.query(`CREATE INDEX "_key_status" ON "functions"."executions" ("status") `);
        await queryRunner.query(`CREATE INDEX "_key_trigger" ON "functions"."executions" ("trigger") `);
        await queryRunner.query(`CREATE INDEX "_fulltext_search" ON "functions"."executions" ("search") `);
        await queryRunner.query(`CREATE INDEX "_key_function" ON "functions"."executions" ("functionId") `);
        await queryRunner.query(`CREATE TABLE "functions"."deployments" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "resourceInternalId" character varying(255), "resourceId" character varying(255), "resourceType" character varying(255), "buildInternalId" character varying(255), "buildId" character varying(255), "entrypoint" character varying(2048), "commands" character varying(2048), "path" character varying(2048), "type" character varying(2048) NOT NULL, "installationId" character varying(255), "installationInternalId" character varying(255), "providerRepositoryId" character varying(255), "repositoryId" character varying(255), "repositoryInternalId" character varying(255), "providerRepositoryName" character varying(255), "providerRepositoryOwner" character varying(255), "providerRepositoryUrl" character varying(255), "providerCommitHash" character varying(255), "providerCommitAuthorUrl" character varying(255), "providerCommitAuthor" character varying(255), "providerCommitMessage" character varying(255), "providerCommitUrl" character varying(255), "providerBranch" character varying(255), "providerBranchUrl" character varying(255), "providerRootDirectory" character varying(255), "providerCommentId" character varying(2048), "size" integer, "metadata" character varying(16384), "chunksTotal" integer, "chunksUploaded" integer, "activate" boolean DEFAULT false, CONSTRAINT "PK_476583c0b82980ab0d27745aa42" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_key_activate" ON "functions"."deployments" ("activate") `);
        await queryRunner.query(`CREATE INDEX "_key_buildId" ON "functions"."deployments" ("buildId") `);
        await queryRunner.query(`CREATE INDEX "_key_size" ON "functions"."deployments" ("size") `);
        await queryRunner.query(`CREATE INDEX "_key_search" ON "functions"."deployments" ("search") `);
        await queryRunner.query(`CREATE INDEX "_key_resource_type" ON "functions"."deployments" ("resourceType") `);
        await queryRunner.query(`CREATE INDEX "_key_resource" ON "functions"."deployments" ("resourceId") `);
        await queryRunner.query(`CREATE TABLE "functions"."builds" ("_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "permissions" character varying(255) array NOT NULL DEFAULT '{}', "search" character varying(16384), "startTime" TIMESTAMP WITH TIME ZONE, "endTime" TIMESTAMP WITH TIME ZONE, "duration" integer, "size" integer, "deploymentInternalId" character varying(255), "deploymentId" character varying(255), "runtime" character varying(2048) NOT NULL, "status" character varying(256) NOT NULL DEFAULT 'processing', "path" character varying(2048), "logs" character varying(1000000), "sourceType" character varying(2048) NOT NULL DEFAULT 'local', "source" character varying(2048) NOT NULL, CONSTRAINT "PK_be032ab38204b0a8de93816fef7" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "_key_deployment" ON "functions"."builds" ("deploymentId") `);
        await queryRunner.query(`ALTER TABLE "auth"."tokens" ADD CONSTRAINT "FK_54ff822a5a8ac32ef4c49a76b55" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."authenticators" ADD CONSTRAINT "FK_9f658d52b5b51725e9fdf02754e" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."challenges" ADD CONSTRAINT "FK_de22071a992c5c7ff4023613d77" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."sessions" ADD CONSTRAINT "FK_0241275d44a68db4bd17d664f9b" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" ADD CONSTRAINT "FK_b82143094ef22e3a9605c50572f" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" ADD CONSTRAINT "FK_a35ff890a1533ad8d876f97a85a" FOREIGN KEY ("team_$id") REFERENCES "auth"."teams"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages"."targets" ADD CONSTRAINT "FK_accb05b1b1318e8ee3e77c32885" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages"."targets" ADD CONSTRAINT "FK_52274d7655547e3b80282d51242" FOREIGN KEY ("provider_$id") REFERENCES "messages"."providers"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."identities" ADD CONSTRAINT "FK_72f58820dfff251d2c00a5e5fd7" FOREIGN KEY ("user_$id") REFERENCES "auth"."users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage"."files" ADD CONSTRAINT "FK_cf1ab2cde469c77ab39d21ff2d8" FOREIGN KEY ("bucket_$id") REFERENCES "storage"."buckets"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "storage"."files" DROP CONSTRAINT "FK_cf1ab2cde469c77ab39d21ff2d8"`);
        await queryRunner.query(`ALTER TABLE "auth"."identities" DROP CONSTRAINT "FK_72f58820dfff251d2c00a5e5fd7"`);
        await queryRunner.query(`ALTER TABLE "messages"."targets" DROP CONSTRAINT "FK_52274d7655547e3b80282d51242"`);
        await queryRunner.query(`ALTER TABLE "messages"."targets" DROP CONSTRAINT "FK_accb05b1b1318e8ee3e77c32885"`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" DROP CONSTRAINT "FK_a35ff890a1533ad8d876f97a85a"`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" DROP CONSTRAINT "FK_b82143094ef22e3a9605c50572f"`);
        await queryRunner.query(`ALTER TABLE "auth"."sessions" DROP CONSTRAINT "FK_0241275d44a68db4bd17d664f9b"`);
        await queryRunner.query(`ALTER TABLE "auth"."challenges" DROP CONSTRAINT "FK_de22071a992c5c7ff4023613d77"`);
        await queryRunner.query(`ALTER TABLE "auth"."authenticators" DROP CONSTRAINT "FK_9f658d52b5b51725e9fdf02754e"`);
        await queryRunner.query(`ALTER TABLE "auth"."tokens" DROP CONSTRAINT "FK_54ff822a5a8ac32ef4c49a76b55"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_deployment"`);
        await queryRunner.query(`DROP TABLE "functions"."builds"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_resource"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_resource_type"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_search"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_size"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_buildId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_activate"`);
        await queryRunner.query(`DROP TABLE "functions"."deployments"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_function"`);
        await queryRunner.query(`DROP INDEX "functions"."_fulltext_search"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_trigger"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_status"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_requestMethod"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_requestPath"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_deploymentId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_responseStatusCode"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_duration"`);
        await queryRunner.query(`DROP TABLE "functions"."executions"`);
        await queryRunner.query(`DROP INDEX "functions"."_key__search"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_name"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_enabled"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_installationId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_installationInternalId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_providerRepositoryId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_repositoryId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_repositoryInternalId"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_runtime"`);
        await queryRunner.query(`DROP INDEX "functions"."_key_idx_deployment"`);
        await queryRunner.query(`DROP TABLE "functions"."functions"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_provider_type"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_status"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_scheduled_at"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_schedule_internal_id"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_schedule_id"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_35000359daf153b15b27ee21e2"`);
        await queryRunner.query(`DROP TABLE "messages"."messages"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_fd461838f998443c5441989db5"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_d966300036db0e1ac00fa51c32"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_3b5f276933ed75028216a4a843"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_3e82da94a504e2d6dff5c9f393"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_64f26a3234a4bac78f6b6e9523"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_1198809f29d22accb0143684ff"`);
        await queryRunner.query(`DROP TABLE "messages"."subscribers"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_bfced34fec53fd4205673bec3f"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_d8e7903f3a8a0a28a49f6b4886"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_a1d014cb180d27ab17fc21be50"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_389d4090f38da709582e7e3a95"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_aacdd3a68ed158c5b526d67276"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_332d10755187ac3c580e21fbc0"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_03457cb4a0bd785d24201481f6"`);
        await queryRunner.query(`DROP TABLE "storage"."files"`);
        await queryRunner.query(`DROP TABLE "storage"."buckets"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_NAME"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_EMAIL"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_PHONE"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_STATUS"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_PASSWORD_UPDATE"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_REGISTRATION"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_EMAIL_VERIFICATION"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_PHONE_VERIFICATION"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_SEARCH"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_ACCESSED_AT"`);
        await queryRunner.query(`DROP TABLE "auth"."users"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_userInternalId_provider_providerUid"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_provider_providerUid"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_userId"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_userInternalId"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_provider"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_providerUid"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_providerEmail"`);
        await queryRunner.query(`DROP INDEX "auth"."_key_providerAccessTokenExpiry"`);
        await queryRunner.query(`DROP TABLE "auth"."identities"`);
        await queryRunner.query(`DROP TABLE "messages"."targets"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_06250375d112fc6ec96ca3ee7c"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_e6e65bb1ecd94653de7b16bb80"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_d735474e539e674ba3702eddc4"`);
        await queryRunner.query(`DROP TABLE "messages"."providers"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_1304b1c61016e63f60cd147ce6"`);
        await queryRunner.query(`DROP TABLE "messages"."topics"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_dba610eddac5ad4aed9a1f15a0"`);
        await queryRunner.query(`DROP INDEX "auth"."user_index"`);
        await queryRunner.query(`DROP INDEX "auth"."team_index"`);
        await queryRunner.query(`DROP INDEX "auth"."search_index"`);
        await queryRunner.query(`DROP INDEX "auth"."userId_index"`);
        await queryRunner.query(`DROP INDEX "auth"."teamId_index"`);
        await queryRunner.query(`DROP INDEX "auth"."invited_index"`);
        await queryRunner.query(`DROP INDEX "auth"."joined_index"`);
        await queryRunner.query(`DROP INDEX "auth"."confirm_index"`);
        await queryRunner.query(`DROP TABLE "auth"."memberships"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_d6ada59c75ff2761704cccebd8"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_48c0c32e6247a2de155baeaf98"`);
        await queryRunner.query(`DROP TABLE "auth"."teams"`);
        await queryRunner.query(`DROP TABLE "auth"."sessions"`);
        await queryRunner.query(`DROP INDEX "auth"."idx_user_id"`);
        await queryRunner.query(`DROP TABLE "auth"."challenges"`);
        await queryRunner.query(`DROP TABLE "auth"."authenticators"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_54ff822a5a8ac32ef4c49a76b5"`);
        await queryRunner.query(`DROP TABLE "auth"."tokens"`);
        await queryRunner.query(`DROP INDEX "meta"."IDX_4f56ebcf8cba238205136aa00f"`);
        await queryRunner.query(`DROP TABLE "meta"."databases"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_status"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_stage"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_source"`);
        await queryRunner.query(`DROP INDEX "meta"."_fulltext__search"`);
        await queryRunner.query(`DROP TABLE "meta"."migrations"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_time"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_period_time"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_metric_period_time"`);
        await queryRunner.query(`DROP TABLE "meta"."stats"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_resourceInternalId"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_resourceType"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_resourceId_resourceType"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_uniqueKey"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_key"`);
        await queryRunner.query(`DROP INDEX "meta"."_fulltext_search"`);
        await queryRunner.query(`DROP TABLE "meta"."variables"`);
    }

}

